### ISSUE TITLE
Improve package not found message

### ISSUE THREAD

**Issue by jeffkl** [CommonBuildToolset/CBT.Modules#225]
_From @ndrwrbgs on March 2, 2018 8:57_

The current message is not very clear:

```
The "GenerateNuGetProperties" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at CBT.NuGet.Internal.NuGetPackageReferenceProjectParser.TryGetPackages(String packageConfigPath, PackageRestoreData packageRestoreData, IEnumerable`1& packages)
   at CBT.NuGet.Internal.NuGetPropertyGenerator.<>c__DisplayClass5_2.<Generate>b__0(INuGetPackageConfigParser i)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CBT.NuGet.Internal.NuGetPropertyGenerator.Generate(String outputPath, String propertyVersionNamePrefix, String propertyPathNamePrefix, PackageRestoreData restoreData)
   at CBT.NuGet.Tasks.GenerateNuGetProperties.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

_Copied from original issue: CommonBuildToolset/CBT.Core#113_

**Comment by jeffkl** [comment]
@ndrwrbgs Thanks for reporting the issue, can you verify you're using the latest version of CBT.NuGet which is 2.1.33?  I _think_ we might have fixed this already just looking at the stack trace.  If you're already running the latest, I'll debug the issue and get it fixed.

**Comment by ndrwrbgs** [comment]
Looks like I picked my version up from another internal project (I didn't see directions saying I needed this file :( ). I had `<PackageReference Include="CBT.NuGet" Version="2.1.15" />`. I will update thanks!

**Comment by ndrwrbgs** [comment]
Validated fixed in the latest, this issue can be closed. Thanks Jeff!

**Comment by jeffkl** [comment]
Awesome, glad to hear it.
