### ISSUE TITLE
exception on retry for missing package.

### ISSUE THREAD

**Issue by paulgmiller** [CommonBuildToolset/CBT.Modules#237]
If you get a missing package on a build. The go shove said package into the feed. then rebuild you'll get  a InvalidOperationException. 

We're on  <PackageReference Include="CBT.NuGet" Version="2.1.29" /> Seing if I should upgrade that. 

msbuild /v:m
Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Restore CBT modules:
MSBUILD : error : NU1102: Unable to find package System.Security.Principal.Windows with version (>= 4.5.0-preview2-26406-04)
MSBUILD : error :   - Found 6 version(s) in NugetMirror [ Nearest version: 4.4.1 ]
MSBUILD : error :   - Found 4 version(s) in OSS_All [ Nearest version: 4.4.1 ]
MSBUILD : error :   - Found 1 version(s) in Bing [ Nearest version: 4.5.0-preview1-26216-02 ]

MSBUILD : error : Errors in E:\src\aether2\src\aether\platform\backendV2\shared\Microsoft.Aether.BackendCommon\Microsoft.Aether.BackendCommon.csproj
MSBUILD : error :     NU1102: Unable to find package System.Security.Principal.Windows with version (>= 4.5.0-preview2-26406-04)
MSBUILD : error :       - Found 6 version(s) in NugetMirror [ Nearest version: 4.4.1 ]
MSBUILD : error :       - Found 4 version(s) in OSS_All [ Nearest version: 4.4.1 ]
E:\src\aether2\.build\CBT\build.props(96,5): error CBT.NuGet.1000: NuGet packages were not restored and the build cannot continue.  Refer to other errors for  more information. [E:\src\aether2\src\aether\platform\backendV2\shared\Microsoft.Aether.BackendCommon\Microsoft.Aether.BackendCommon.csproj]

11:18:22 E:\src\aether2\src\aether\platform\backendV2\shared\Microsoft.Aether.BackendCommon
>msbuild /v:m
Microsoft (R) Build Engine version 15.6.85.37198 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error : System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no matching element
MSBUILD : error :    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
MSBUILD : error :    at CBT.NuGet.Internal.NuGetPackageReferenceProjectParser.TryGetPackages(String packageConfigPath, PackageRestoreData packageRestoreData,  IEnumerable`1& packages)

**Comment by paulgmiller** [comment]
Moving up to 2.1.35 didn't help. Same error. 
System.InvalidOperationException: Sequence contains no matching element
MSBUILD : error :    at System.Linq.Enumerable.First[TSource]

**Comment by paulgmiller** [comment]
Oh and doing a git clean on just the dir get you 
 Missing expected NuGet assets file 'E:\src\ aether2\src\aether\platform\backendV2\shared\Microsoft.Aether.BackendCommon\project.assets.json'.
